# Uncomment the next line to define a global platform for your project
platform :ios, '16.0'

target 'TopShot Match' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TopShot Match
  pod 'FCL-SDK', :git => 'https://github.com/chase1745/fcl-swift.git', :commit => 'a43c66a2433e90ff95ae4a051110bf74dab816a8'

end

