# Uncomment the next line to define a global platform for your project
platform :ios, '16.0'

target 'TopShot Match' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TopShot Match
  pod 'FCL-SDK', '~> 0.3.3'

end

